# Generated by Django 5.1.4 on 2025-01-13 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_book_author_alter_book_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarians', to='libraries.library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librarians', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
